### ISSUE TITLE
Dynamic styling/theming?

### ISSUE THREAD

**Issue by kiaran918** [JLogical-Apps/flood#6]
Hi, I just started using this and firstly just wanted to say it's an amazing job you've done and thank you for all the hard work! I'm usually a C# developer using WPF and Blazor, but recently started working with Flutter for cross platform app development, and Flood has been a blessing for getting things done rapidly yet in a neat and structured manner.

I was wondering if there is any easy way to modify the style/theme of the app while it's running, without having to restart the app? With a standard `MaterialApp` using `ListenableBuilder`, I believe you can achieve this by modifying the `theme`/`themeMode` parameter it references and call `notifyListeners()` from an object that mixins with `ChangeNotifier` (set as the `listenable`) to rebuild/draw everything. Is there any easy substitute to this that I can try? I tried making a style wrapper object that has an internal swappable style but changing that had no effect. The use-case I need this for is to allow switching between dark/light modes manually by the user but also implement accessibility features (e.g. high contrast/dyslexic fonts/etc.). Any help would be much appreciated – many thanks in advance!

**Comment by jaboyc** [comment]
Hi @kiaran918, yes, this is unfortunately one of the limitations of the Style Module in Flood. Believe it or not, none of the apps I've built with Flood needed a dynamic theme switcher, so it was never implemented, but it is something I've had on my to-do list for a while. Currently, there really isn't a way to work around this issue as [StyleProvider](https://github.com/JLogical-Apps/flood/blob/v4.1/packages/style/lib/src/style_provider.dart) doesn't react to changes in the Style, and [StyleAppComponent](https://github.com/JLogical-Apps/flood/blob/v4.1/packages/pond/modules/style_component/lib/src/style_app_component.dart) only accepts one Style when initializing the app. I'm not entirely sure what the best solution to changing Styles dynamically with Flood will be, let me know if you have any suggestions! Due to your need of having more than just light/dark theme, I'll aim to keep it really flexible, but still allow developers to easily just whip out a light/dark mode if that's all they need.

I've started the processing of preparing for the v4.2 release, but I'll go ahead and add dynamic theme switching in there as well so that you'll have a solution ready soon. I'm aiming to have v4.2 released sometime this week, so stay tuned! I'll keep this issue open until then.

**Comment by jaboyc** [comment]
Hey @kiaran918, I've gone ahead and added dynamic theme switching to v4.2! 

[Here's a commit](https://github.com/JLogical-Apps/flood-example/commit/910ca4faf6438b72276daf8099f63f58189971cd#diff-7814135d909c501b64220072bb844ab26eb0b418262660f2784cb40a7395b9a6) you can use as reference for how to add dynamic theme switching to your app! This commit in the example repo adds light and dark theme to an app, but it should be flexible to add whatever themes you need to add! It also listens to the `theme` property of the logged-in user and updates the theme of the app if that property ever changes.

When initializing the `FloodAppComponent` in `main.dart`, the `style` parameter indicates the initial Style to load during the splash screen. If you add a `styleLoader`, you can load a style based on dynamic values, such as a theme stored in the currently logged-in user (as in the example commit above), or you can use SharedPreferences or wherever else you'd like to store this info!

To change the style of the app, simply call `context.styleAppComponent.style = myNewStyle`, and the app will update to reflect the new style!

I will officially release v4.2 sometime later this week with more details, let me know if this approach works for you and if you have any other questions!

**Comment by kiaran918** [comment]
Thank you so much @jaboyc, I just tried this out by switching to v4.2 and toggling between `Style`s from a button following your test code, and it works like a charm, truly amazing!
