### ISSUE TITLE
Installation Errors using Melos and Mason

### ISSUE THREAD

**Issue by jeff9315** [JLogical-Apps/flood#7]
When I open up the project in VSCode for the 1st time, I get an error that the melos.yaml file is invalid.

name: todo1
repository:                                                                          **// LOOKS LIKE THIS SHOULD contain a String ... Incorrect type.** Expected "string | object(melos.yaml)".

packages:
  - todo1
  - todo1_core

command:
  bootstrap:
    usePubspecOverrides: true                                        **// LOOKS LIKE THIS HAS BEEN DEPRECATED ... Property** usePubspecOverrides is not allowed.

scripts:
  test:
    name: test
    description: 'Run all tests'
    run: |
      melos exec -fail-fast                                  - flutter analyze . && \
      melos exec -fail-fast --dir-exists="test" --no-flutter - flutter test . && \
      melos exec -fail-fast --dir-exists="test" --flutter    - flutter test .

**Comment by jaboyc** [comment]
Hi @jeff9315, thanks for pointing that out. I do my Flutter development on Android Studio, which does not have a Melos validator (that I'm aware of). 

When you run `mason make flood`, it will ask "What is the URL of your Github repo?", which is then used in the `repository` field. It looks like you skipped that during the setup process, so that field is blank.

Even though `repository` is blank and `usePubspecOverrides` is deprecated, `melos bs` should still run (I've been running it fine with the latest version of Melos, even with blank `repository` values). I'll remove the depcrecated `usePubspecOverrides: true` for the next version of the template and Mason brick, but this should not impact your Flood development.

Let me know if these are causing any issues in your project and I would be glad to help! Closing for now.
