### ISSUE TITLE
Installation error with dependency override and all import statements fail

### ISSUE THREAD

**Issue by jeff9315** [JLogical-Apps/flood#9]
OK ... I've gotten past the other errors. Now I'm left with this dependency override and all import statement fail including flutter/material.dart and all flood imports and even local file imports. Thanks for all your help in just getting me started with your package.

Jeff
```
Resolving dependencies... (1.0s)
Because every version of flood_cli from git depends on flood_core from git git@github.com:JLogical-Apps/flood.git at v4.2 in packages/flood/flood_core and       
  todo6 depends on flood_core from git https://github.com/JLogical-Apps/flood.git at v4.2 in packages/flood/flood_core, flood_cli from git is forbidden.
So, because todo6 depends on flood_cli from git, version solving failed.
```

```
Target of URI doesn't exist: 'package:flood/flood.dart'.
target of URI doesn't exist: 'package:flutter/material.dart'.
Target of URI doesn't exist: 'package:todo6/presentation/style.dart'.
```

**Comment by jaboyc** [comment]
Hi @jeff9315, thanks for pointing this out. It looks like my previous suggestion of using https://github.com/JLogical-Apps/flood.git doesn't work, since internally, Flood uses git@github.com:JLogical-Apps/flood.git to reference the repository. Sorry for the confusion, that was my bad.

It looks like you'll need to switch back to using git@github.com:JLogical-Apps/flood.git in your `pubspec.yaml` files, and follow these instructions to add SSH keys to your Github account.

> ## Add an SSH Key to Your GitHub Account
> 
> Generate a new SSH key:
> https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
> 
> Add the SSH key to your GitHub account:
> https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
> 

I've gone ahead and edited my response to the [previous issue](https://github.com/JLogical-Apps/flood/issues/8) to prevent confusion from anyone else dealing with this issue in the future. Thank you for your patience.

Will close for now, let me know if you run into any more issues!
